- name: install influxdb
  apt:
    deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.2_amd64.deb
  when: ansible_distribution == 'Debian'

- name: copy config file
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf

- name: start influxdb
  systemd:
    name: influxdb
    state: restarted
    enabled: true
    daemon_reload: true

