- name: Instalamos requisitos
  apt:
    name:
      - adduser
      - libfontconfig1

- name: Instalamos grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.1.5_amd64.deb
  register: grafanapkg

- name: start grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
  when: grafanapkg.changed

- name: Descargamos y configuramos histou
  shell: |
    cd /tmp
    wget -O histou.tar.gz https://github.com/Griesbacher/histou/archive/v0.4.3.tar.gz
    mkdir -p /var/www/html/histou
    cd /var/www/html/histou
    tar xzf /tmp/histou.tar.gz --strip-components 1
    cp histou.ini.example histou.ini
    cp histou.js /usr/share/grafana/public/dashboards/
    sed -i 's/localhost/{{ ansible_hostname }}.mono.lan/g' /usr/share/grafana/public/dashboards/histou.js

