all:
  children:
    laptops:
      hosts:
        arkadia:

    baremetal:
      hosts:
        odroid:
          ansible_host: 192.168.1.5
          ansible_python_interpreter: /usr/bin/python3
        pve:
        pi:
          ansible_host: 192.168.1.8

    virtual:
      hosts:
        bree:
        mithlond:
        comarca:
        masdiseno:
        nagios:
        rohan:

    autoupdate:
      children:
        baremetal:
        virtual:

    linux:
      children:
        laptops:
        baremetal:
        virtual:

