---
- name: restart nagios
  systemd:
    name: nagios
    state: restarted

- name: restart nagflux
  systemd:
    name: nagflux
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart apache
  systemd:
    name: apache2
    state: restarted

