- name: "Ensure localisation files for 'en_US.UTF-8' are available"
  locale_gen:
    name: "en_US.UTF-8"
    state: present

- name: Configure locales
  command: localectl set-locale LANG="C.UTF-8" LC_COLLATE=C LC_CTYPE=C LANGUAGE="en_US.UTF-8"
