- name: Ensure localisation files for 'en_US.UTF-8' are available
  locale_gen:
    name: "en_US.UTF-8"
    state: present

- name: Configure locale to 'C' and language to 'en_US.UTF-8'
  command: localectl set-locale LANG=C LANGUAGE=en_US.UTF-8
