---
- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 800
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: if ubuntu, install software-properties-common
  package:
    name:
      - software-properties-common
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: if ubuntu, add universe repo
  command: "add-apt-repository universe"
  when: ansible_distribution == 'Ubuntu'

- name: install common packages
  package:
    name:
      - htop
      - rsync
      - dstat
      - jq
      - sysstat
      - bc
    state: latest

- name: install required packages for Debian
  package:
    name:
      - vim-nox
      - python3-pip
      - python3-setuptools
    state: latest
  when: ansible_distribution == 'Debian'

- name: "sshd listens in local network ({{ ansible_default_ipv4.address }})"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ListenAddress'
    insertafter: '^#ListenAddress'
    line: ListenAddress {{ ansible_default_ipv4.address }}
  when:
    - ansible_hostname != 'odroid'
    - ansible_distribution == 'Deshabilitado'
  register: sshdlisten

- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: sshdlisten.changed

- name: Instalamos acl para poder pasar a usuario no privilegiado
  apt:
    name: acl
    state: present
  when: ansible_distribution == 'Debian'

- name: Modificamos el swappiness
  sysctl:
    name: vm.swappiness
    value: {{ swappiness.value }}
    state: present
    reload: yes
    sysctl_set: yes
  when:
    - swapiness.value is defined
    - ansible_hostname in ['pve', 'rohan']

- name: Instalamos qemu-guest-agent en las VM
  apt:
    name: qemu-guest-agent
    state: present
  when:
    - ansible_distribution == 'Debian'
    - qemu_agent|default(false)|bool == true

- name: Iniciamos qemu-agent
  systemd:
    daemon-reload: yes
    name: qemu-guest-agent
    state: started
  when: qemu_agent|default(false)|bool == true

- name: Copiamos config por defecto para vim
  copy:
    src: vimrc
    dest: "{{ item }}"
  with_items:
    - /etc/vimrc
    - /usr/share/vim/vimrc

- name: Copiamos el script pre-reboot.sh (si existe)
  copy:
    src: "root/{{ ansible_hostname }}_pre-reboot.sh"
    dest: /usr/local/bin/pre-reboot.sh
    owner: root
    group: root
    mode: 0774
  when: "(role_path + '/files/root/' + ansible_hostname + '_pre-reboot.sh') is is_file"

- name: Copiamos los crones (si existen)
  copy:
    src: "crons/{{ ansible_hostname }}/"
    dest: /etc/cron.d
    owner: root
    group: root
    mode: 0644
  when: "(role_path + '/files/crons/' + ansible_hostname) is is_dir"

- include: tmpfs.yml
  when:
    - ansible_distribution == 'Deshabilitado'

- include: sysstat.yml
  when:
    - ansible_distribution == 'Deshabilitado'

- name: Modificamos capacidad de journald
  blockinfile:
    path: /etc/systemd/journald.conf
    block: |
      Storage=volatile
      RuntimeMaxUse=20M
      ForwardToSyslog=no
    insertafter: '[Journal]'
  register: jcfg
  when:
    - server_type == 'virtual'

- name: Restart journald
  systemd:
    name: systemd-journald
    state: restarted
  when: jcfg.changed

- name: Customize bash
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      alias ls='ls --color=auto'
      alias dir='dir --color=auto'
      alias vdir='vdir --color=auto'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'

      if [ $UID -ne 0 ]; then
          alias sudo='sudo ' # passes aliases over to root when using sudo
      fi

      shopt -s checkwinsize
      alias ls='ls -hF --color=auto --group-directories-first'
      alias la='ls -A'
      alias ll='ls -lh'
      alias l='ls -alh'
      alias lr='ls -R'

- include: locale.yml
