- name: Deshabilitamos sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="false"'

- name: Configuramos /etc/sysstat/sysstat
  lineinfile:
    path: /etc/sysstat/sysstat
    regexp: '^SADC_OPTIONS='
    line: 'SADC_OPTIONS="-S XALL"'

- name: Configuramos /etc/sysstat/sysstat
  lineinfile:
    path: /etc/sysstat/sysstat
    regexp: '^HISTORY='
    line: 'HISTORY=2'

- name: Habilitamos sysstat
  systemd:
    name: sysstat
    state: started
    enabled: true
    daemon_reload: true
