---
- name: add syncthing user
  user:
    name: "{{ syncthing_user }}"
    shell: /bin/bash
    uid: "{{ syncthing_uid }}"
    group: "{{ syncthing_group }}"

- name: Add an Apt signing key for syncthing
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add syncthing repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing.list

- name: Update cache and upgrade dist
  apt:
    upgrade: dist
    update_cache: yes

- name: install syncthing
  package:
    name:
      - syncthing
    state: latest

- name: install syncthing systemd unit file
  template:
    src: syncthing.service.j2
    dest: /lib/systemd/system/syncthing.service
    owner: root
    group: root
    mode: '0644'
  register: sync_serv

- name: start syncthing
  service:
    name: syncthing
    daemon_reload: yes
    state: started
  when: sync_serv.changed
  register: syncstart

- name: let the service start
  pause:
    seconds: 10
  when: syncstart is defined and syncstart.changed

- name: replace syncthing's default path
  replace:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    regexp: '<defaultFolderPath>(.*)</defaultFolderPath>'
    replace: '<defaultFolderPath>{{ syncthing_path }}</defaultFolderPath>'
    owner: "{{ syncthing_user }}"

- name: replace syncthing's browser startup
  replace:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    regexp: '<startBrowser>true</startBrowser>'
    replace: '<startBrowser>false</startBrowser>'
    owner: "{{ syncthing_user }}"

- name: replace syncthing's listening address
  replace:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    after: '<gui'
    before: '</gui>'
    regexp: '<address>(.*)</address>'
    replace: "<address>{{ ansible_default_ipv4.address }}:{{ syncthing_webui_port }}</address>"
    owner: "{{ syncthing_user }}"

- name: replace syncthing's tls
  replace:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    after: '<gui'
    before: '</gui>'
    regexp: 'tls="(.*)"'
    replace: 'tls="true"'
    owner: "{{ syncthing_user }}"

- name: listenaddress
  lineinfile:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    insertafter: "<options>"
    regexp: ' *<listenAddress>tcp.*$'
    line: "        <listenAddress>tcp://:{{ syncthing_main_port }}</listenAddress>"

- name: listenaddress 2
  lineinfile:
    path: "/home/{{ syncthing_user }}/.config/syncthing/config.xml"
    insertafter: "<listenAddress>tcp://:{{ syncthing_main_port }}</listenAddress>"
    regexp: ' *<listenAddress>dynamic.*>$'
    line: "        <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>"

- name: restart syncthing
  service:
    name: syncthing
    enabled: yes
    state: restarted

